version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=root
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis

  app:
    build:
      context: .
    environment:
      - LOCAL_DATABASE_HOST=postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
