services:
  app:
    build: .
    environment:
      - LOCAL_DATABASE_HOST=postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: rails s -b 0.0.0.0
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=root
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis
